name = "Hugo-Primer"
license = "MIT"
licenselink = "https://github.com/ress997/hugo-primer/blob/master/LICENSE"
description = "A simple and beautiful Hugo theme based on GitHub's Primer CSS"
homepage = "https://github.com/ress997/hugo-primer"
tags = ["blog", "simple", "minimal", "clean", "personal", "syntax highlighting", "white", "light", "simple page", "technical"]
features = ["blog", "toc", "code pen", "syntax highlighting", "math", "math inline", "tags", "categories", "social", "share", "share button", "social share"]
# Hugo version
min_version = 0.65.0

[author]
  name = "Ress"
  homepage = "https://github.com/ress997"

# If porting an existing theme
[original]
  name = "Hugo-Primer"
  homepage = "https://github.com/qqhann/hugo-primer"
  repo = "https://github.com/qqhann/hugo-primer.git"
